on: 
  push:
    branches:
      - develop
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Push
      uses: actions/checkout@v3
      with:
        clean: true
        ref: develop
    - run: |
        git config user.name pecasdesign
        git config user.email hola@pecas.design
        npm i
        npm run generate
        npm run deploy